### PR TITLE
[WIP] New Form elements

### PR DESCRIPTION
**Pull request by Lelith**
Who: @lelith
What / Why: styling of standard input fields and text area also including it inside an example
https://mcmakler.atlassian.net/browse/MC-2401

### CODE REVIEW

**Comment by baruchvlz** [comment]
Rebase the branch with develop.

**Comment by Lelith** [comment]
@baruchvlz hitting the button in this very second.

**Review by TejasQ — APPROVED** [review]

**Review by TejasQ — APPROVED** [review]
LGTM

**Comment by Lelith** [comment]
i need to refactor a little bit as the reusable react components shall get moved to a different repository i close for now and reopen when i am finished

**Pull request closed without merging**
